//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:18:10 PM CEST 
//


package simgrideclipseplugin.model.simgrid;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="suffix" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="radical" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="power" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="core" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="1" />
 *       &lt;attribute name="bw" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sharing_policy" default="FULLDUPLEX">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="SHARED"/>
 *             &lt;enumeration value="FULLDUPLEX"/>
 *             &lt;enumeration value="FATPIPE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="bb_bw" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="bb_lat" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="bb_sharing_policy" default="SHARED">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="SHARED"/>
 *             &lt;enumeration value="FATPIPE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="availability_file" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="state_file" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="router_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "cluster")
public class Cluster {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prefix;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String suffix;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String radical;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String power;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String core;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bw;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lat;
    @XmlAttribute(name = "sharing_policy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sharingPolicy;
    @XmlAttribute(name = "bb_bw")
    @XmlSchemaType(name = "anySimpleType")
    protected String bbBw;
    @XmlAttribute(name = "bb_lat")
    @XmlSchemaType(name = "anySimpleType")
    protected String bbLat;
    @XmlAttribute(name = "bb_sharing_policy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bbSharingPolicy;
    @XmlAttribute(name = "availability_file")
    @XmlSchemaType(name = "anySimpleType")
    protected String availabilityFile;
    @XmlAttribute(name = "state_file")
    @XmlSchemaType(name = "anySimpleType")
    protected String stateFile;
    @XmlAttribute(name = "router_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String routerId;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the radical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadical() {
        return radical;
    }

    /**
     * Sets the value of the radical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadical(String value) {
        this.radical = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPower(String value) {
        this.power = value;
    }

    /**
     * Gets the value of the core property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCore() {
        if (core == null) {
            return "1";
        } else {
            return core;
        }
    }

    /**
     * Sets the value of the core property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCore(String value) {
        this.core = value;
    }

    /**
     * Gets the value of the bw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBw() {
        return bw;
    }

    /**
     * Sets the value of the bw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBw(String value) {
        this.bw = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the sharingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSharingPolicy() {
        if (sharingPolicy == null) {
            return "FULLDUPLEX";
        } else {
            return sharingPolicy;
        }
    }

    /**
     * Sets the value of the sharingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSharingPolicy(String value) {
        this.sharingPolicy = value;
    }

    /**
     * Gets the value of the bbBw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbBw() {
        if (bbBw == null) {
            return "";
        } else {
            return bbBw;
        }
    }

    /**
     * Sets the value of the bbBw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbBw(String value) {
        this.bbBw = value;
    }

    /**
     * Gets the value of the bbLat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbLat() {
        if (bbLat == null) {
            return "";
        } else {
            return bbLat;
        }
    }

    /**
     * Sets the value of the bbLat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbLat(String value) {
        this.bbLat = value;
    }

    /**
     * Gets the value of the bbSharingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbSharingPolicy() {
        if (bbSharingPolicy == null) {
            return "SHARED";
        } else {
            return bbSharingPolicy;
        }
    }

    /**
     * Sets the value of the bbSharingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbSharingPolicy(String value) {
        this.bbSharingPolicy = value;
    }

    /**
     * Gets the value of the availabilityFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityFile() {
        if (availabilityFile == null) {
            return "";
        } else {
            return availabilityFile;
        }
    }

    /**
     * Sets the value of the availabilityFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityFile(String value) {
        this.availabilityFile = value;
    }

    /**
     * Gets the value of the stateFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateFile() {
        if (stateFile == null) {
            return "";
        } else {
            return stateFile;
        }
    }

    /**
     * Sets the value of the stateFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateFile(String value) {
        this.stateFile = value;
    }

    /**
     * Gets the value of the routerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouterId() {
        if (routerId == null) {
            return "";
        } else {
            return routerId;
        }
    }

    /**
     * Sets the value of the routerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouterId(String value) {
        this.routerId = value;
    }

}
