//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:18:10 PM CEST 
//


package simgrideclipseplugin.model.simgrid;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="power" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bw_in" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bw_out" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="coordinates" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="availability_file" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="state_file" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "peer")
public class Peer {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String power;
    @XmlAttribute(name = "bw_in", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bwIn;
    @XmlAttribute(name = "bw_out", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bwOut;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lat;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String coordinates;
    @XmlAttribute(name = "availability_file")
    @XmlSchemaType(name = "anySimpleType")
    protected String availabilityFile;
    @XmlAttribute(name = "state_file")
    @XmlSchemaType(name = "anySimpleType")
    protected String stateFile;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPower(String value) {
        this.power = value;
    }

    /**
     * Gets the value of the bwIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBwIn() {
        return bwIn;
    }

    /**
     * Sets the value of the bwIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBwIn(String value) {
        this.bwIn = value;
    }

    /**
     * Gets the value of the bwOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBwOut() {
        return bwOut;
    }

    /**
     * Sets the value of the bwOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBwOut(String value) {
        this.bwOut = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the coordinates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinates() {
        if (coordinates == null) {
            return "";
        } else {
            return coordinates;
        }
    }

    /**
     * Sets the value of the coordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinates(String value) {
        this.coordinates = value;
    }

    /**
     * Gets the value of the availabilityFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityFile() {
        if (availabilityFile == null) {
            return "";
        } else {
            return availabilityFile;
        }
    }

    /**
     * Sets the value of the availabilityFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityFile(String value) {
        this.availabilityFile = value;
    }

    /**
     * Gets the value of the stateFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateFile() {
        if (stateFile == null) {
            return "";
        } else {
            return stateFile;
        }
    }

    /**
     * Sets the value of the stateFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateFile(String value) {
        this.stateFile = value;
    }

}
