//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:18:10 PM CEST 
//


package simgrideclipseplugin.model.simgrid;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}config"/>
 *           &lt;element ref="{}random"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}include"/>
 *           &lt;element ref="{}cluster"/>
 *           &lt;element ref="{}peer"/>
 *           &lt;element ref="{}AS"/>
 *           &lt;element ref="{}trace"/>
 *           &lt;element ref="{}trace_connect"/>
 *         &lt;/choice>
 *         &lt;element ref="{}process" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configOrRandom",
    "includeOrClusterOrPeer",
    "process"
})
@XmlRootElement(name = "platform")
public class Platform {

    @XmlElements({
        @XmlElement(name = "config", type = Config.class),
        @XmlElement(name = "random", type = Random.class)
    })
    protected List<Object> configOrRandom;
    @XmlElements({
        @XmlElement(name = "trace_connect", type = TraceConnect.class),
        @XmlElement(name = "AS", type = AS.class),
        @XmlElement(name = "peer", type = Peer.class),
        @XmlElement(name = "cluster", type = Cluster.class),
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "trace", type = Trace.class)
    })
    protected List<Object> includeOrClusterOrPeer;
    protected List<Process> process;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String version;

    /**
     * Gets the value of the configOrRandom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configOrRandom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigOrRandom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Config }
     * {@link Random }
     * 
     * 
     */
    public List<Object> getConfigOrRandom() {
        if (configOrRandom == null) {
            configOrRandom = new ArrayList<Object>();
        }
        return this.configOrRandom;
    }

    /**
     * Gets the value of the includeOrClusterOrPeer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeOrClusterOrPeer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeOrClusterOrPeer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TraceConnect }
     * {@link AS }
     * {@link Peer }
     * {@link Cluster }
     * {@link Include }
     * {@link Trace }
     * 
     * 
     */
    public List<Object> getIncludeOrClusterOrPeer() {
        if (includeOrClusterOrPeer == null) {
            includeOrClusterOrPeer = new ArrayList<Object>();
        }
        return this.includeOrClusterOrPeer;
    }

    /**
     * Gets the value of the process property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the process property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Process }
     * 
     * 
     */
    public List<Process> getProcess() {
        if (process == null) {
            process = new ArrayList<Process>();
        }
        return this.process;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
