//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:18:10 PM CEST 
//


package simgrideclipseplugin.model.simgrid;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}argument"/>
 *         &lt;element ref="{}prop"/>
 *       &lt;/choice>
 *       &lt;attribute name="host" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="function" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="start_time" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="-1.0" />
 *       &lt;attribute name="kill_time" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="-1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "argumentOrProp"
})
@XmlRootElement(name = "process")
public class Process {

    @XmlElements({
        @XmlElement(name = "prop", type = Prop.class),
        @XmlElement(name = "argument", type = Argument.class)
    })
    protected List<Object> argumentOrProp;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String host;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String function;
    @XmlAttribute(name = "start_time")
    @XmlSchemaType(name = "anySimpleType")
    protected String startTime;
    @XmlAttribute(name = "kill_time")
    @XmlSchemaType(name = "anySimpleType")
    protected String killTime;

    /**
     * Gets the value of the argumentOrProp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argumentOrProp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgumentOrProp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prop }
     * {@link Argument }
     * 
     * 
     */
    public List<Object> getArgumentOrProp() {
        if (argumentOrProp == null) {
            argumentOrProp = new ArrayList<Object>();
        }
        return this.argumentOrProp;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        if (startTime == null) {
            return "-1.0";
        } else {
            return startTime;
        }
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the killTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKillTime() {
        if (killTime == null) {
            return "-1.0";
        } else {
            return killTime;
        }
    }

    /**
     * Sets the value of the killTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKillTime(String value) {
        this.killTime = value;
    }

}
